sudo: false
language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - cmake-3.6.4111459

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk
  - export ANDROID_NDK_HOME=$HOME/android-ndk

script:
  - ./gradlew testDebugUnitTest

